<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aEBsystem" nsURI="http://www.example.org/aEBsystem" nsPrefix="aEBsystem">
  <eClassifiers xsi:type="ecore:EClass" name="AEBSystem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="systemID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operatingMode" eType="#//OperatingMode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensors" upperBound="-1"
        eType="#//Sensor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controller" eType="#//Controller"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actuators" upperBound="-1"
        eType="#//Actuator" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environmentconditions"
        upperBound="-1" eType="#//EnvironmentCondition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperatingMode">
    <eLiterals name="Normal"/>
    <eLiterals name="Emergency" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sensorType" eType="#//SensorType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="range" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accuracy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="detectionEvents" upperBound="-1"
        eType="#//DetectionEvent" containment="true" eOpposite="#//DetectionEvent/triggeredBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Controller">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dicisionLatency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//EmergencyActions" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//SafetyConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actuator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ActuatorType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxForce" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//EmergencyActions" eOpposite="#//EmergencyActions/executedBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SensorType">
    <eLiterals name="Radar"/>
    <eLiterals name="Lidar" value="1"/>
    <eLiterals name="Camera" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DetectionEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="confidence" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggeredBy" eType="#//Sensor"
        eOpposite="#//Sensor/detectionEvents"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="obstacle" eType="#//Obstacle"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Obstacle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="obstacleType" eType="#//ObstacleType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ObstacleType">
    <eLiterals name="Vehicle"/>
    <eLiterals name="Pedestrian" value="1"/>
    <eLiterals name="Static" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="State">
    <eLiterals name="Idle"/>
    <eLiterals name="Assessing" value="1"/>
    <eLiterals name="Acting" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmergencyActions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionType" eType="#//ActionType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executedBy" eType="#//Actuator"
        eOpposite="#//Actuator/actions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActionType">
    <eLiterals name="Brake"/>
    <eLiterals name="Warn" value="1"/>
    <eLiterals name="Steer" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActuatorType">
    <eLiterals name="Brake"/>
    <eLiterals name="Horn" value="1"/>
    <eLiterals name="Steering" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SafetyConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraintType" eType="#//ConstraintType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isCritical" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appliesTo" upperBound="-1"
        eType="#//EmergencyActions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConstraintType">
    <eLiterals name="Timing"/>
    <eLiterals name="Distance" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnvironmentCondition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conditionType" eType="#//ConditionType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="severity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="affects" upperBound="-1"
        eType="#//Sensor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConditionType">
    <eLiterals name="Rain"/>
    <eLiterals name="Fog" value="1"/>
    <eLiterals name="Night" value="2"/>
  </eClassifiers>
</ecore:EPackage>
